### ISSUE TITLE
Problem with Executing `npm run build` Using `esbuild` & `Node` 17.6.0 - "The Callback Was Already Called"

### ISSUE THREAD

**Issue by FilipWozniak** [AccordBox/python-webpack-boilerplate#30]
I regularly configure the project using "Python Webpack Boilerplate" guide. More specifically, I install Wagtail (Django), run `npm` command at `frontend` directory, enable live reloading feature, import Vue and also enable `esbuild`. I have always used `Node 14.19.0`, but lately  thought to give you a chance of a newer version - `17.6.0`. At the time of executing `npm run build` command, I get the following error:

```
/Users/filip/Desktop/dj-wgt/wgt/frontend/node_modules/loader-runner/lib/LoaderRunner.js:119
			throw new Error("callback(): The callback was already called.");
			      ^
Error: callback(): The callback was already called.
    at context.callback (/Users/filip/Desktop/dj-wgt/wgt/frontend/node_modules/loader-runner/lib/LoaderRunner.js:119:10)
    at Object.ESBuildLoader (/Users/filip/Desktop/dj-wgt/wgt/frontend/node_modules/esbuild-loader/dist/loader.js:62:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

<img width="971" alt="image" src="https://user-images.githubusercontent.com/64541581/157019373-47d47d5b-8198-4b78-8c2e-f4390c2dd9d4.png">

I don't use Docker. I use `Python 3.9.0`, though.

Any ideas how to solve this issue?

**Comment by FilipWozniak** [comment]
It turned out that running `npm outdate` revealed a few outdated packages. 

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/64541581/157021437-d18c6ca4-585d-49cc-913f-06a3e1e0aa72.png">

So the solution was as easy as executing `npm update`.
